# your GitHub user name
username: Cheukting

# public repos that you want to showcase
repos:
  - PyO3/pyo3
  - pola-rs/polars

# ===== SVG file settings =====

# output svg file name
output: output.svg

# status of the PR that would be included: all, open, closed
state: all

# style of the card: full, compact
style: full

apperance:

  # title (optional)
  title: My Contributions in Rust

  # prioritized list of one or more font family names and/or generic family names seperated by commas (optional)
  fonts: Arial, Helvetica, sans-serif

  # size multiplyer: non-negative, recommend 0.8-1.5
  size: 1

  # color of the background (optional), if not given it will be transparent
  bg_color: "#696969"

  # The radius of the corners of the background: non-negative, recommend 5-15
  bg_r: 8

  # primary color
  pri_color: "#FFC0CB"

  # secondary color
  sec_color: "#CBB39C"

# ===== Social Media settings (optional) =====
# post new pr/ merged pr to your social media account. Please see README for method to set up access tokens and secrets (required).

social:

  # X (Twitter) handle e.g. @example
  twitter: "@cheukting_ho"

  # Mastodon handle e.g. @example@demo.org
  mastodon: "@cheukting_ho@fosstodon.org"

  # LinkedIn profile page e.g. https://www.linkedin.com/in/<your_name>/
  linkedin: https://www.linkedin.com/in/cheukting-ho/
