name: Generate SVG file
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "10 9 * * *" # <=== Change this value 
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Run script
        env:
          TOKEN: ${{ secrets.Token }}
        run: |
          sudo apt-get install ghostscript
          sudo apt-get install potrace
          pip install -r requirements.txt
          python main.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated: $(date +'%Y-%m-%dT%H:%M:%S')"
          git push
